package main

const (
	envCryptoKey          = "MVDL_CRYKEY"
	envAddr               = "ADDR"
	envPageSize           = "PAGE_SIZE"
	envUpstreamTimeout    = "UPSTREAM_TIMEOUT"
	envKnabenAPIURL       = "KNABEN_API_URL"
	envTMDBAPIKey         = "MVDL_TMDB_APIKEY"
	envTMDBAPIURL         = "TMDB_API_URL"
	envTorrentClawAPIKey  = "TORRENTCLAW_API_KEY"
	envTorrentClawAPIURL  = "TORRENTCLAW_API_URL"
	defaultKnabenAPIURL   = "https://api.knaben.org/v1"
	defaultTorrentClawURL = "https://torrentclaw.com/api/v1"
	defaultTMDBAPIURL     = "https://api.themoviedb.org/3"

	FlagPageSize             = "page-size"
	FlagListen               = "listen"
	FlagProvider             = "provider"
	FlagFilter               = "filter"
	FlagTimeout              = "timeout"
	FlagSaveTo               = "save-to"
	FlagConnections          = "connections"
	FlagHalfOpen             = "half-open"
	FlagTotalHalfOpen        = "total-half-open"
	FlagPeerHighWater        = "peer-high-water"
	FlagPeerLowWater         = "peer-low-water"
	FlagDialRate             = "dial-rate"
	FlagMaxUnverifiedMiB     = "max-unverified-mib"
	FlagPeerRequestBufferMiB = "peer-request-buffer-mib"
	FlagPieceHashers         = "piece-hashers"
	FlagTorrentListen        = "torrent-listen"
	FlagNoUpload             = "no-upload"
	FlagSeed                 = "seed"
	FlagDisableIPv6          = "disable-ipv6"
	FlagDownloadRateMiB      = "download-rate-mib"
	FlagUploadRateMiB        = "upload-rate-mib"
	FlagProgressInterval     = "progress-interval"
	FlagStatusListen         = "status-listen"
	FlagMovie                = "movie"
	FlagTV                   = "tv"
	FlagLanguage             = "language"

	DefaultListenAddr = "127.0.0.1:6567"

	SubCmdDownload = "download"
	SubCmdQuery    = "query"
	SubCmdServer   = "server"
	SubCmdTMDB     = "tmdb"
)
