name: Docker Build

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  docker-build:
    name: docker build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build image
        run: docker build --pull --tag mvdl:${{ github.sha }} .
